/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './pages/__root'
import { Route as YamlJsonConverterRouteImport } from './pages/yamlJsonConverter'
import { Route as WordCounterRouteImport } from './pages/wordCounter'
import { Route as WebsocketClientRouteImport } from './pages/websocketClient'
import { Route as WatermarkRouteImport } from './pages/watermark'
import { Route as VideoToGifRouteImport } from './pages/videoToGif'
import { Route as UuidGeneratorRouteImport } from './pages/uuidGenerator'
import { Route as UrlParserRouteImport } from './pages/urlParser'
import { Route as UnitConverterRouteImport } from './pages/unitConverter'
import { Route as TimestampConverterRouteImport } from './pages/timestampConverter'
import { Route as TextDiffRouteImport } from './pages/textDiff'
import { Route as SymmetricCryptoRouteImport } from './pages/symmetricCrypto'
import { Route as StringEncoderRouteImport } from './pages/stringEncoder'
import { Route as ScssConverterRouteImport } from './pages/scssConverter'
import { Route as RsaKeyGeneratorRouteImport } from './pages/rsaKeyGenerator'
import { Route as RandomGeneratorRouteImport } from './pages/randomGenerator'
import { Route as QrGeneratorRouteImport } from './pages/qrGenerator'
import { Route as PortTableRouteImport } from './pages/portTable'
import { Route as PdfToWordRouteImport } from './pages/pdfToWord'
import { Route as PdfSplitter_newRouteImport } from './pages/pdfSplitter_new'
import { Route as PdfSplitterRouteImport } from './pages/pdfSplitter'
import { Route as PdfMergerRouteImport } from './pages/pdfMerger'
import { Route as PasswordGeneratorRouteImport } from './pages/passwordGenerator'
import { Route as MusicPlayerRouteImport } from './pages/musicPlayer'
import { Route as MqttClientRouteImport } from './pages/mqttClient'
import { Route as MarkdownToWechatRouteImport } from './pages/markdownToWechat'
import { Route as LeafletMapRouteImport } from './pages/leafletMap'
import { Route as JwtGeneratorRouteImport } from './pages/jwtGenerator'
import { Route as JwtDecoderRouteImport } from './pages/jwtDecoder'
import { Route as JsonFormatterRouteImport } from './pages/jsonFormatter'
import { Route as JsFormatterRouteImport } from './pages/jsFormatter'
import { Route as ImageToPdfRouteImport } from './pages/imageToPdf'
import { Route as ImageMetadataRouteImport } from './pages/imageMetadata'
import { Route as ImageGalleryRouteImport } from './pages/imageGallery'
import { Route as ImageCompressorRouteImport } from './pages/imageCompressor'
import { Route as HttpStatusRouteImport } from './pages/httpStatus'
import { Route as HttpHeadersRouteImport } from './pages/httpHeaders'
import { Route as HtmlJsConverterRouteImport } from './pages/htmlJsConverter'
import { Route as HexStringConverterRouteImport } from './pages/hexStringConverter'
import { Route as HashCalculatorRouteImport } from './pages/hashCalculator'
import { Route as GradientGeneratorRouteImport } from './pages/gradientGenerator'
import { Route as FileUploaderRouteImport } from './pages/fileUploader'
import { Route as DateCalculatorRouteImport } from './pages/dateCalculator'
import { Route as CsvJsonConverterRouteImport } from './pages/csvJsonConverter'
import { Route as CssFormatterRouteImport } from './pages/cssFormatter'
import { Route as ColorConverterRouteImport } from './pages/colorConverter'
import { Route as CaseConverterRouteImport } from './pages/caseConverter'
import { Route as BrowserTabsRouteImport } from './pages/browserTabs'
import { Route as BaseConverterRouteImport } from './pages/baseConverter'
import { Route as Base64ConverterRouteImport } from './pages/base64Converter'
import { Route as AudioMd5RouteImport } from './pages/audioMd5'
import { Route as AsciiTableRouteImport } from './pages/asciiTable'
import { Route as AboutRouteImport } from './pages/about'
import { Route as SpeechToTextRouteImport } from './pages/SpeechToText'
import { Route as IndexRouteImport } from './pages/index'

const SignatureLazyRouteImport = createFileRoute('/signature')()
const JsonToTsLazyRouteImport = createFileRoute('/jsonToTs')()
const CoordinateLazyRouteImport = createFileRoute('/coordinate')()
const CalculateDistanceLazyRouteImport = createFileRoute('/calculateDistance')()

const SignatureLazyRoute = SignatureLazyRouteImport.update({
  id: '/signature',
  path: '/signature',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/signature.lazy').then((d) => d.Route))
const JsonToTsLazyRoute = JsonToTsLazyRouteImport.update({
  id: '/jsonToTs',
  path: '/jsonToTs',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/jsonToTs.lazy').then((d) => d.Route))
const CoordinateLazyRoute = CoordinateLazyRouteImport.update({
  id: '/coordinate',
  path: '/coordinate',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pages/coordinate.lazy').then((d) => d.Route))
const CalculateDistanceLazyRoute = CalculateDistanceLazyRouteImport.update({
  id: '/calculateDistance',
  path: '/calculateDistance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./pages/calculateDistance.lazy').then((d) => d.Route),
)
const YamlJsonConverterRoute = YamlJsonConverterRouteImport.update({
  id: '/yamlJsonConverter',
  path: '/yamlJsonConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const WordCounterRoute = WordCounterRouteImport.update({
  id: '/wordCounter',
  path: '/wordCounter',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsocketClientRoute = WebsocketClientRouteImport.update({
  id: '/websocketClient',
  path: '/websocketClient',
  getParentRoute: () => rootRouteImport,
} as any)
const WatermarkRoute = WatermarkRouteImport.update({
  id: '/watermark',
  path: '/watermark',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoToGifRoute = VideoToGifRouteImport.update({
  id: '/videoToGif',
  path: '/videoToGif',
  getParentRoute: () => rootRouteImport,
} as any)
const UuidGeneratorRoute = UuidGeneratorRouteImport.update({
  id: '/uuidGenerator',
  path: '/uuidGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const UrlParserRoute = UrlParserRouteImport.update({
  id: '/urlParser',
  path: '/urlParser',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitConverterRoute = UnitConverterRouteImport.update({
  id: '/unitConverter',
  path: '/unitConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const TimestampConverterRoute = TimestampConverterRouteImport.update({
  id: '/timestampConverter',
  path: '/timestampConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const TextDiffRoute = TextDiffRouteImport.update({
  id: '/textDiff',
  path: '/textDiff',
  getParentRoute: () => rootRouteImport,
} as any)
const SymmetricCryptoRoute = SymmetricCryptoRouteImport.update({
  id: '/symmetricCrypto',
  path: '/symmetricCrypto',
  getParentRoute: () => rootRouteImport,
} as any)
const StringEncoderRoute = StringEncoderRouteImport.update({
  id: '/stringEncoder',
  path: '/stringEncoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ScssConverterRoute = ScssConverterRouteImport.update({
  id: '/scssConverter',
  path: '/scssConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const RsaKeyGeneratorRoute = RsaKeyGeneratorRouteImport.update({
  id: '/rsaKeyGenerator',
  path: '/rsaKeyGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomGeneratorRoute = RandomGeneratorRouteImport.update({
  id: '/randomGenerator',
  path: '/randomGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qrGenerator',
  path: '/qrGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const PortTableRoute = PortTableRouteImport.update({
  id: '/portTable',
  path: '/portTable',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdfToWord',
  path: '/pdfToWord',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfSplitter_newRoute = PdfSplitter_newRouteImport.update({
  id: '/pdfSplitter_new',
  path: '/pdfSplitter_new',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfSplitterRoute = PdfSplitterRouteImport.update({
  id: '/pdfSplitter',
  path: '/pdfSplitter',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfMergerRoute = PdfMergerRouteImport.update({
  id: '/pdfMerger',
  path: '/pdfMerger',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/passwordGenerator',
  path: '/passwordGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicPlayerRoute = MusicPlayerRouteImport.update({
  id: '/musicPlayer',
  path: '/musicPlayer',
  getParentRoute: () => rootRouteImport,
} as any)
const MqttClientRoute = MqttClientRouteImport.update({
  id: '/mqttClient',
  path: '/mqttClient',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownToWechatRoute = MarkdownToWechatRouteImport.update({
  id: '/markdownToWechat',
  path: '/markdownToWechat',
  getParentRoute: () => rootRouteImport,
} as any)
const LeafletMapRoute = LeafletMapRouteImport.update({
  id: '/leafletMap',
  path: '/leafletMap',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtGeneratorRoute = JwtGeneratorRouteImport.update({
  id: '/jwtGenerator',
  path: '/jwtGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const JwtDecoderRoute = JwtDecoderRouteImport.update({
  id: '/jwtDecoder',
  path: '/jwtDecoder',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/jsonFormatter',
  path: '/jsonFormatter',
  getParentRoute: () => rootRouteImport,
} as any)
const JsFormatterRoute = JsFormatterRouteImport.update({
  id: '/jsFormatter',
  path: '/jsFormatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/imageToPdf',
  path: '/imageToPdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageMetadataRoute = ImageMetadataRouteImport.update({
  id: '/imageMetadata',
  path: '/imageMetadata',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGalleryRoute = ImageGalleryRouteImport.update({
  id: '/imageGallery',
  path: '/imageGallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/imageCompressor',
  path: '/imageCompressor',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpStatusRoute = HttpStatusRouteImport.update({
  id: '/httpStatus',
  path: '/httpStatus',
  getParentRoute: () => rootRouteImport,
} as any)
const HttpHeadersRoute = HttpHeadersRouteImport.update({
  id: '/httpHeaders',
  path: '/httpHeaders',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlJsConverterRoute = HtmlJsConverterRouteImport.update({
  id: '/htmlJsConverter',
  path: '/htmlJsConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const HexStringConverterRoute = HexStringConverterRouteImport.update({
  id: '/hexStringConverter',
  path: '/hexStringConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const HashCalculatorRoute = HashCalculatorRouteImport.update({
  id: '/hashCalculator',
  path: '/hashCalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const GradientGeneratorRoute = GradientGeneratorRouteImport.update({
  id: '/gradientGenerator',
  path: '/gradientGenerator',
  getParentRoute: () => rootRouteImport,
} as any)
const FileUploaderRoute = FileUploaderRouteImport.update({
  id: '/fileUploader',
  path: '/fileUploader',
  getParentRoute: () => rootRouteImport,
} as any)
const DateCalculatorRoute = DateCalculatorRouteImport.update({
  id: '/dateCalculator',
  path: '/dateCalculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvJsonConverterRoute = CsvJsonConverterRouteImport.update({
  id: '/csvJsonConverter',
  path: '/csvJsonConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const CssFormatterRoute = CssFormatterRouteImport.update({
  id: '/cssFormatter',
  path: '/cssFormatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorConverterRoute = ColorConverterRouteImport.update({
  id: '/colorConverter',
  path: '/colorConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseConverterRoute = CaseConverterRouteImport.update({
  id: '/caseConverter',
  path: '/caseConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserTabsRoute = BrowserTabsRouteImport.update({
  id: '/browserTabs',
  path: '/browserTabs',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseConverterRoute = BaseConverterRouteImport.update({
  id: '/baseConverter',
  path: '/baseConverter',
  getParentRoute: () => rootRouteImport,
} as any)
const Base64ConverterRoute = Base64ConverterRouteImport.update({
  id: '/base64Converter',
  path: '/base64Converter',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioMd5Route = AudioMd5RouteImport.update({
  id: '/audioMd5',
  path: '/audioMd5',
  getParentRoute: () => rootRouteImport,
} as any)
const AsciiTableRoute = AsciiTableRouteImport.update({
  id: '/asciiTable',
  path: '/asciiTable',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechToTextRoute = SpeechToTextRouteImport.update({
  id: '/SpeechToText',
  path: '/SpeechToText',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/SpeechToText': typeof SpeechToTextRoute
  '/about': typeof AboutRoute
  '/asciiTable': typeof AsciiTableRoute
  '/audioMd5': typeof AudioMd5Route
  '/base64Converter': typeof Base64ConverterRoute
  '/baseConverter': typeof BaseConverterRoute
  '/browserTabs': typeof BrowserTabsRoute
  '/caseConverter': typeof CaseConverterRoute
  '/colorConverter': typeof ColorConverterRoute
  '/cssFormatter': typeof CssFormatterRoute
  '/csvJsonConverter': typeof CsvJsonConverterRoute
  '/dateCalculator': typeof DateCalculatorRoute
  '/fileUploader': typeof FileUploaderRoute
  '/gradientGenerator': typeof GradientGeneratorRoute
  '/hashCalculator': typeof HashCalculatorRoute
  '/hexStringConverter': typeof HexStringConverterRoute
  '/htmlJsConverter': typeof HtmlJsConverterRoute
  '/httpHeaders': typeof HttpHeadersRoute
  '/httpStatus': typeof HttpStatusRoute
  '/imageCompressor': typeof ImageCompressorRoute
  '/imageGallery': typeof ImageGalleryRoute
  '/imageMetadata': typeof ImageMetadataRoute
  '/imageToPdf': typeof ImageToPdfRoute
  '/jsFormatter': typeof JsFormatterRoute
  '/jsonFormatter': typeof JsonFormatterRoute
  '/jwtDecoder': typeof JwtDecoderRoute
  '/jwtGenerator': typeof JwtGeneratorRoute
  '/leafletMap': typeof LeafletMapRoute
  '/markdownToWechat': typeof MarkdownToWechatRoute
  '/mqttClient': typeof MqttClientRoute
  '/musicPlayer': typeof MusicPlayerRoute
  '/passwordGenerator': typeof PasswordGeneratorRoute
  '/pdfMerger': typeof PdfMergerRoute
  '/pdfSplitter': typeof PdfSplitterRoute
  '/pdfSplitter_new': typeof PdfSplitter_newRoute
  '/pdfToWord': typeof PdfToWordRoute
  '/portTable': typeof PortTableRoute
  '/qrGenerator': typeof QrGeneratorRoute
  '/randomGenerator': typeof RandomGeneratorRoute
  '/rsaKeyGenerator': typeof RsaKeyGeneratorRoute
  '/scssConverter': typeof ScssConverterRoute
  '/stringEncoder': typeof StringEncoderRoute
  '/symmetricCrypto': typeof SymmetricCryptoRoute
  '/textDiff': typeof TextDiffRoute
  '/timestampConverter': typeof TimestampConverterRoute
  '/unitConverter': typeof UnitConverterRoute
  '/urlParser': typeof UrlParserRoute
  '/uuidGenerator': typeof UuidGeneratorRoute
  '/videoToGif': typeof VideoToGifRoute
  '/watermark': typeof WatermarkRoute
  '/websocketClient': typeof WebsocketClientRoute
  '/wordCounter': typeof WordCounterRoute
  '/yamlJsonConverter': typeof YamlJsonConverterRoute
  '/calculateDistance': typeof CalculateDistanceLazyRoute
  '/coordinate': typeof CoordinateLazyRoute
  '/jsonToTs': typeof JsonToTsLazyRoute
  '/signature': typeof SignatureLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/SpeechToText': typeof SpeechToTextRoute
  '/about': typeof AboutRoute
  '/asciiTable': typeof AsciiTableRoute
  '/audioMd5': typeof AudioMd5Route
  '/base64Converter': typeof Base64ConverterRoute
  '/baseConverter': typeof BaseConverterRoute
  '/browserTabs': typeof BrowserTabsRoute
  '/caseConverter': typeof CaseConverterRoute
  '/colorConverter': typeof ColorConverterRoute
  '/cssFormatter': typeof CssFormatterRoute
  '/csvJsonConverter': typeof CsvJsonConverterRoute
  '/dateCalculator': typeof DateCalculatorRoute
  '/fileUploader': typeof FileUploaderRoute
  '/gradientGenerator': typeof GradientGeneratorRoute
  '/hashCalculator': typeof HashCalculatorRoute
  '/hexStringConverter': typeof HexStringConverterRoute
  '/htmlJsConverter': typeof HtmlJsConverterRoute
  '/httpHeaders': typeof HttpHeadersRoute
  '/httpStatus': typeof HttpStatusRoute
  '/imageCompressor': typeof ImageCompressorRoute
  '/imageGallery': typeof ImageGalleryRoute
  '/imageMetadata': typeof ImageMetadataRoute
  '/imageToPdf': typeof ImageToPdfRoute
  '/jsFormatter': typeof JsFormatterRoute
  '/jsonFormatter': typeof JsonFormatterRoute
  '/jwtDecoder': typeof JwtDecoderRoute
  '/jwtGenerator': typeof JwtGeneratorRoute
  '/leafletMap': typeof LeafletMapRoute
  '/markdownToWechat': typeof MarkdownToWechatRoute
  '/mqttClient': typeof MqttClientRoute
  '/musicPlayer': typeof MusicPlayerRoute
  '/passwordGenerator': typeof PasswordGeneratorRoute
  '/pdfMerger': typeof PdfMergerRoute
  '/pdfSplitter': typeof PdfSplitterRoute
  '/pdfSplitter_new': typeof PdfSplitter_newRoute
  '/pdfToWord': typeof PdfToWordRoute
  '/portTable': typeof PortTableRoute
  '/qrGenerator': typeof QrGeneratorRoute
  '/randomGenerator': typeof RandomGeneratorRoute
  '/rsaKeyGenerator': typeof RsaKeyGeneratorRoute
  '/scssConverter': typeof ScssConverterRoute
  '/stringEncoder': typeof StringEncoderRoute
  '/symmetricCrypto': typeof SymmetricCryptoRoute
  '/textDiff': typeof TextDiffRoute
  '/timestampConverter': typeof TimestampConverterRoute
  '/unitConverter': typeof UnitConverterRoute
  '/urlParser': typeof UrlParserRoute
  '/uuidGenerator': typeof UuidGeneratorRoute
  '/videoToGif': typeof VideoToGifRoute
  '/watermark': typeof WatermarkRoute
  '/websocketClient': typeof WebsocketClientRoute
  '/wordCounter': typeof WordCounterRoute
  '/yamlJsonConverter': typeof YamlJsonConverterRoute
  '/calculateDistance': typeof CalculateDistanceLazyRoute
  '/coordinate': typeof CoordinateLazyRoute
  '/jsonToTs': typeof JsonToTsLazyRoute
  '/signature': typeof SignatureLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/SpeechToText': typeof SpeechToTextRoute
  '/about': typeof AboutRoute
  '/asciiTable': typeof AsciiTableRoute
  '/audioMd5': typeof AudioMd5Route
  '/base64Converter': typeof Base64ConverterRoute
  '/baseConverter': typeof BaseConverterRoute
  '/browserTabs': typeof BrowserTabsRoute
  '/caseConverter': typeof CaseConverterRoute
  '/colorConverter': typeof ColorConverterRoute
  '/cssFormatter': typeof CssFormatterRoute
  '/csvJsonConverter': typeof CsvJsonConverterRoute
  '/dateCalculator': typeof DateCalculatorRoute
  '/fileUploader': typeof FileUploaderRoute
  '/gradientGenerator': typeof GradientGeneratorRoute
  '/hashCalculator': typeof HashCalculatorRoute
  '/hexStringConverter': typeof HexStringConverterRoute
  '/htmlJsConverter': typeof HtmlJsConverterRoute
  '/httpHeaders': typeof HttpHeadersRoute
  '/httpStatus': typeof HttpStatusRoute
  '/imageCompressor': typeof ImageCompressorRoute
  '/imageGallery': typeof ImageGalleryRoute
  '/imageMetadata': typeof ImageMetadataRoute
  '/imageToPdf': typeof ImageToPdfRoute
  '/jsFormatter': typeof JsFormatterRoute
  '/jsonFormatter': typeof JsonFormatterRoute
  '/jwtDecoder': typeof JwtDecoderRoute
  '/jwtGenerator': typeof JwtGeneratorRoute
  '/leafletMap': typeof LeafletMapRoute
  '/markdownToWechat': typeof MarkdownToWechatRoute
  '/mqttClient': typeof MqttClientRoute
  '/musicPlayer': typeof MusicPlayerRoute
  '/passwordGenerator': typeof PasswordGeneratorRoute
  '/pdfMerger': typeof PdfMergerRoute
  '/pdfSplitter': typeof PdfSplitterRoute
  '/pdfSplitter_new': typeof PdfSplitter_newRoute
  '/pdfToWord': typeof PdfToWordRoute
  '/portTable': typeof PortTableRoute
  '/qrGenerator': typeof QrGeneratorRoute
  '/randomGenerator': typeof RandomGeneratorRoute
  '/rsaKeyGenerator': typeof RsaKeyGeneratorRoute
  '/scssConverter': typeof ScssConverterRoute
  '/stringEncoder': typeof StringEncoderRoute
  '/symmetricCrypto': typeof SymmetricCryptoRoute
  '/textDiff': typeof TextDiffRoute
  '/timestampConverter': typeof TimestampConverterRoute
  '/unitConverter': typeof UnitConverterRoute
  '/urlParser': typeof UrlParserRoute
  '/uuidGenerator': typeof UuidGeneratorRoute
  '/videoToGif': typeof VideoToGifRoute
  '/watermark': typeof WatermarkRoute
  '/websocketClient': typeof WebsocketClientRoute
  '/wordCounter': typeof WordCounterRoute
  '/yamlJsonConverter': typeof YamlJsonConverterRoute
  '/calculateDistance': typeof CalculateDistanceLazyRoute
  '/coordinate': typeof CoordinateLazyRoute
  '/jsonToTs': typeof JsonToTsLazyRoute
  '/signature': typeof SignatureLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/SpeechToText'
    | '/about'
    | '/asciiTable'
    | '/audioMd5'
    | '/base64Converter'
    | '/baseConverter'
    | '/browserTabs'
    | '/caseConverter'
    | '/colorConverter'
    | '/cssFormatter'
    | '/csvJsonConverter'
    | '/dateCalculator'
    | '/fileUploader'
    | '/gradientGenerator'
    | '/hashCalculator'
    | '/hexStringConverter'
    | '/htmlJsConverter'
    | '/httpHeaders'
    | '/httpStatus'
    | '/imageCompressor'
    | '/imageGallery'
    | '/imageMetadata'
    | '/imageToPdf'
    | '/jsFormatter'
    | '/jsonFormatter'
    | '/jwtDecoder'
    | '/jwtGenerator'
    | '/leafletMap'
    | '/markdownToWechat'
    | '/mqttClient'
    | '/musicPlayer'
    | '/passwordGenerator'
    | '/pdfMerger'
    | '/pdfSplitter'
    | '/pdfSplitter_new'
    | '/pdfToWord'
    | '/portTable'
    | '/qrGenerator'
    | '/randomGenerator'
    | '/rsaKeyGenerator'
    | '/scssConverter'
    | '/stringEncoder'
    | '/symmetricCrypto'
    | '/textDiff'
    | '/timestampConverter'
    | '/unitConverter'
    | '/urlParser'
    | '/uuidGenerator'
    | '/videoToGif'
    | '/watermark'
    | '/websocketClient'
    | '/wordCounter'
    | '/yamlJsonConverter'
    | '/calculateDistance'
    | '/coordinate'
    | '/jsonToTs'
    | '/signature'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/SpeechToText'
    | '/about'
    | '/asciiTable'
    | '/audioMd5'
    | '/base64Converter'
    | '/baseConverter'
    | '/browserTabs'
    | '/caseConverter'
    | '/colorConverter'
    | '/cssFormatter'
    | '/csvJsonConverter'
    | '/dateCalculator'
    | '/fileUploader'
    | '/gradientGenerator'
    | '/hashCalculator'
    | '/hexStringConverter'
    | '/htmlJsConverter'
    | '/httpHeaders'
    | '/httpStatus'
    | '/imageCompressor'
    | '/imageGallery'
    | '/imageMetadata'
    | '/imageToPdf'
    | '/jsFormatter'
    | '/jsonFormatter'
    | '/jwtDecoder'
    | '/jwtGenerator'
    | '/leafletMap'
    | '/markdownToWechat'
    | '/mqttClient'
    | '/musicPlayer'
    | '/passwordGenerator'
    | '/pdfMerger'
    | '/pdfSplitter'
    | '/pdfSplitter_new'
    | '/pdfToWord'
    | '/portTable'
    | '/qrGenerator'
    | '/randomGenerator'
    | '/rsaKeyGenerator'
    | '/scssConverter'
    | '/stringEncoder'
    | '/symmetricCrypto'
    | '/textDiff'
    | '/timestampConverter'
    | '/unitConverter'
    | '/urlParser'
    | '/uuidGenerator'
    | '/videoToGif'
    | '/watermark'
    | '/websocketClient'
    | '/wordCounter'
    | '/yamlJsonConverter'
    | '/calculateDistance'
    | '/coordinate'
    | '/jsonToTs'
    | '/signature'
  id:
    | '__root__'
    | '/'
    | '/SpeechToText'
    | '/about'
    | '/asciiTable'
    | '/audioMd5'
    | '/base64Converter'
    | '/baseConverter'
    | '/browserTabs'
    | '/caseConverter'
    | '/colorConverter'
    | '/cssFormatter'
    | '/csvJsonConverter'
    | '/dateCalculator'
    | '/fileUploader'
    | '/gradientGenerator'
    | '/hashCalculator'
    | '/hexStringConverter'
    | '/htmlJsConverter'
    | '/httpHeaders'
    | '/httpStatus'
    | '/imageCompressor'
    | '/imageGallery'
    | '/imageMetadata'
    | '/imageToPdf'
    | '/jsFormatter'
    | '/jsonFormatter'
    | '/jwtDecoder'
    | '/jwtGenerator'
    | '/leafletMap'
    | '/markdownToWechat'
    | '/mqttClient'
    | '/musicPlayer'
    | '/passwordGenerator'
    | '/pdfMerger'
    | '/pdfSplitter'
    | '/pdfSplitter_new'
    | '/pdfToWord'
    | '/portTable'
    | '/qrGenerator'
    | '/randomGenerator'
    | '/rsaKeyGenerator'
    | '/scssConverter'
    | '/stringEncoder'
    | '/symmetricCrypto'
    | '/textDiff'
    | '/timestampConverter'
    | '/unitConverter'
    | '/urlParser'
    | '/uuidGenerator'
    | '/videoToGif'
    | '/watermark'
    | '/websocketClient'
    | '/wordCounter'
    | '/yamlJsonConverter'
    | '/calculateDistance'
    | '/coordinate'
    | '/jsonToTs'
    | '/signature'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpeechToTextRoute: typeof SpeechToTextRoute
  AboutRoute: typeof AboutRoute
  AsciiTableRoute: typeof AsciiTableRoute
  AudioMd5Route: typeof AudioMd5Route
  Base64ConverterRoute: typeof Base64ConverterRoute
  BaseConverterRoute: typeof BaseConverterRoute
  BrowserTabsRoute: typeof BrowserTabsRoute
  CaseConverterRoute: typeof CaseConverterRoute
  ColorConverterRoute: typeof ColorConverterRoute
  CssFormatterRoute: typeof CssFormatterRoute
  CsvJsonConverterRoute: typeof CsvJsonConverterRoute
  DateCalculatorRoute: typeof DateCalculatorRoute
  FileUploaderRoute: typeof FileUploaderRoute
  GradientGeneratorRoute: typeof GradientGeneratorRoute
  HashCalculatorRoute: typeof HashCalculatorRoute
  HexStringConverterRoute: typeof HexStringConverterRoute
  HtmlJsConverterRoute: typeof HtmlJsConverterRoute
  HttpHeadersRoute: typeof HttpHeadersRoute
  HttpStatusRoute: typeof HttpStatusRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  ImageGalleryRoute: typeof ImageGalleryRoute
  ImageMetadataRoute: typeof ImageMetadataRoute
  ImageToPdfRoute: typeof ImageToPdfRoute
  JsFormatterRoute: typeof JsFormatterRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  JwtDecoderRoute: typeof JwtDecoderRoute
  JwtGeneratorRoute: typeof JwtGeneratorRoute
  LeafletMapRoute: typeof LeafletMapRoute
  MarkdownToWechatRoute: typeof MarkdownToWechatRoute
  MqttClientRoute: typeof MqttClientRoute
  MusicPlayerRoute: typeof MusicPlayerRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  PdfMergerRoute: typeof PdfMergerRoute
  PdfSplitterRoute: typeof PdfSplitterRoute
  PdfSplitter_newRoute: typeof PdfSplitter_newRoute
  PdfToWordRoute: typeof PdfToWordRoute
  PortTableRoute: typeof PortTableRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  RandomGeneratorRoute: typeof RandomGeneratorRoute
  RsaKeyGeneratorRoute: typeof RsaKeyGeneratorRoute
  ScssConverterRoute: typeof ScssConverterRoute
  StringEncoderRoute: typeof StringEncoderRoute
  SymmetricCryptoRoute: typeof SymmetricCryptoRoute
  TextDiffRoute: typeof TextDiffRoute
  TimestampConverterRoute: typeof TimestampConverterRoute
  UnitConverterRoute: typeof UnitConverterRoute
  UrlParserRoute: typeof UrlParserRoute
  UuidGeneratorRoute: typeof UuidGeneratorRoute
  VideoToGifRoute: typeof VideoToGifRoute
  WatermarkRoute: typeof WatermarkRoute
  WebsocketClientRoute: typeof WebsocketClientRoute
  WordCounterRoute: typeof WordCounterRoute
  YamlJsonConverterRoute: typeof YamlJsonConverterRoute
  CalculateDistanceLazyRoute: typeof CalculateDistanceLazyRoute
  CoordinateLazyRoute: typeof CoordinateLazyRoute
  JsonToTsLazyRoute: typeof JsonToTsLazyRoute
  SignatureLazyRoute: typeof SignatureLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signature': {
      id: '/signature'
      path: '/signature'
      fullPath: '/signature'
      preLoaderRoute: typeof SignatureLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonToTs': {
      id: '/jsonToTs'
      path: '/jsonToTs'
      fullPath: '/jsonToTs'
      preLoaderRoute: typeof JsonToTsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinate': {
      id: '/coordinate'
      path: '/coordinate'
      fullPath: '/coordinate'
      preLoaderRoute: typeof CoordinateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateDistance': {
      id: '/calculateDistance'
      path: '/calculateDistance'
      fullPath: '/calculateDistance'
      preLoaderRoute: typeof CalculateDistanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yamlJsonConverter': {
      id: '/yamlJsonConverter'
      path: '/yamlJsonConverter'
      fullPath: '/yamlJsonConverter'
      preLoaderRoute: typeof YamlJsonConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wordCounter': {
      id: '/wordCounter'
      path: '/wordCounter'
      fullPath: '/wordCounter'
      preLoaderRoute: typeof WordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/websocketClient': {
      id: '/websocketClient'
      path: '/websocketClient'
      fullPath: '/websocketClient'
      preLoaderRoute: typeof WebsocketClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watermark': {
      id: '/watermark'
      path: '/watermark'
      fullPath: '/watermark'
      preLoaderRoute: typeof WatermarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videoToGif': {
      id: '/videoToGif'
      path: '/videoToGif'
      fullPath: '/videoToGif'
      preLoaderRoute: typeof VideoToGifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uuidGenerator': {
      id: '/uuidGenerator'
      path: '/uuidGenerator'
      fullPath: '/uuidGenerator'
      preLoaderRoute: typeof UuidGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urlParser': {
      id: '/urlParser'
      path: '/urlParser'
      fullPath: '/urlParser'
      preLoaderRoute: typeof UrlParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unitConverter': {
      id: '/unitConverter'
      path: '/unitConverter'
      fullPath: '/unitConverter'
      preLoaderRoute: typeof UnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timestampConverter': {
      id: '/timestampConverter'
      path: '/timestampConverter'
      fullPath: '/timestampConverter'
      preLoaderRoute: typeof TimestampConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textDiff': {
      id: '/textDiff'
      path: '/textDiff'
      fullPath: '/textDiff'
      preLoaderRoute: typeof TextDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symmetricCrypto': {
      id: '/symmetricCrypto'
      path: '/symmetricCrypto'
      fullPath: '/symmetricCrypto'
      preLoaderRoute: typeof SymmetricCryptoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stringEncoder': {
      id: '/stringEncoder'
      path: '/stringEncoder'
      fullPath: '/stringEncoder'
      preLoaderRoute: typeof StringEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scssConverter': {
      id: '/scssConverter'
      path: '/scssConverter'
      fullPath: '/scssConverter'
      preLoaderRoute: typeof ScssConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsaKeyGenerator': {
      id: '/rsaKeyGenerator'
      path: '/rsaKeyGenerator'
      fullPath: '/rsaKeyGenerator'
      preLoaderRoute: typeof RsaKeyGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/randomGenerator': {
      id: '/randomGenerator'
      path: '/randomGenerator'
      fullPath: '/randomGenerator'
      preLoaderRoute: typeof RandomGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qrGenerator': {
      id: '/qrGenerator'
      path: '/qrGenerator'
      fullPath: '/qrGenerator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portTable': {
      id: '/portTable'
      path: '/portTable'
      fullPath: '/portTable'
      preLoaderRoute: typeof PortTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfToWord': {
      id: '/pdfToWord'
      path: '/pdfToWord'
      fullPath: '/pdfToWord'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfSplitter_new': {
      id: '/pdfSplitter_new'
      path: '/pdfSplitter_new'
      fullPath: '/pdfSplitter_new'
      preLoaderRoute: typeof PdfSplitter_newRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfSplitter': {
      id: '/pdfSplitter'
      path: '/pdfSplitter'
      fullPath: '/pdfSplitter'
      preLoaderRoute: typeof PdfSplitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdfMerger': {
      id: '/pdfMerger'
      path: '/pdfMerger'
      fullPath: '/pdfMerger'
      preLoaderRoute: typeof PdfMergerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passwordGenerator': {
      id: '/passwordGenerator'
      path: '/passwordGenerator'
      fullPath: '/passwordGenerator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicPlayer': {
      id: '/musicPlayer'
      path: '/musicPlayer'
      fullPath: '/musicPlayer'
      preLoaderRoute: typeof MusicPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mqttClient': {
      id: '/mqttClient'
      path: '/mqttClient'
      fullPath: '/mqttClient'
      preLoaderRoute: typeof MqttClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdownToWechat': {
      id: '/markdownToWechat'
      path: '/markdownToWechat'
      fullPath: '/markdownToWechat'
      preLoaderRoute: typeof MarkdownToWechatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leafletMap': {
      id: '/leafletMap'
      path: '/leafletMap'
      fullPath: '/leafletMap'
      preLoaderRoute: typeof LeafletMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwtGenerator': {
      id: '/jwtGenerator'
      path: '/jwtGenerator'
      fullPath: '/jwtGenerator'
      preLoaderRoute: typeof JwtGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jwtDecoder': {
      id: '/jwtDecoder'
      path: '/jwtDecoder'
      fullPath: '/jwtDecoder'
      preLoaderRoute: typeof JwtDecoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsonFormatter': {
      id: '/jsonFormatter'
      path: '/jsonFormatter'
      fullPath: '/jsonFormatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jsFormatter': {
      id: '/jsFormatter'
      path: '/jsFormatter'
      fullPath: '/jsFormatter'
      preLoaderRoute: typeof JsFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imageToPdf': {
      id: '/imageToPdf'
      path: '/imageToPdf'
      fullPath: '/imageToPdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imageMetadata': {
      id: '/imageMetadata'
      path: '/imageMetadata'
      fullPath: '/imageMetadata'
      preLoaderRoute: typeof ImageMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imageGallery': {
      id: '/imageGallery'
      path: '/imageGallery'
      fullPath: '/imageGallery'
      preLoaderRoute: typeof ImageGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imageCompressor': {
      id: '/imageCompressor'
      path: '/imageCompressor'
      fullPath: '/imageCompressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/httpStatus': {
      id: '/httpStatus'
      path: '/httpStatus'
      fullPath: '/httpStatus'
      preLoaderRoute: typeof HttpStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/httpHeaders': {
      id: '/httpHeaders'
      path: '/httpHeaders'
      fullPath: '/httpHeaders'
      preLoaderRoute: typeof HttpHeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/htmlJsConverter': {
      id: '/htmlJsConverter'
      path: '/htmlJsConverter'
      fullPath: '/htmlJsConverter'
      preLoaderRoute: typeof HtmlJsConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hexStringConverter': {
      id: '/hexStringConverter'
      path: '/hexStringConverter'
      fullPath: '/hexStringConverter'
      preLoaderRoute: typeof HexStringConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hashCalculator': {
      id: '/hashCalculator'
      path: '/hashCalculator'
      fullPath: '/hashCalculator'
      preLoaderRoute: typeof HashCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gradientGenerator': {
      id: '/gradientGenerator'
      path: '/gradientGenerator'
      fullPath: '/gradientGenerator'
      preLoaderRoute: typeof GradientGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fileUploader': {
      id: '/fileUploader'
      path: '/fileUploader'
      fullPath: '/fileUploader'
      preLoaderRoute: typeof FileUploaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dateCalculator': {
      id: '/dateCalculator'
      path: '/dateCalculator'
      fullPath: '/dateCalculator'
      preLoaderRoute: typeof DateCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csvJsonConverter': {
      id: '/csvJsonConverter'
      path: '/csvJsonConverter'
      fullPath: '/csvJsonConverter'
      preLoaderRoute: typeof CsvJsonConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cssFormatter': {
      id: '/cssFormatter'
      path: '/cssFormatter'
      fullPath: '/cssFormatter'
      preLoaderRoute: typeof CssFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colorConverter': {
      id: '/colorConverter'
      path: '/colorConverter'
      fullPath: '/colorConverter'
      preLoaderRoute: typeof ColorConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caseConverter': {
      id: '/caseConverter'
      path: '/caseConverter'
      fullPath: '/caseConverter'
      preLoaderRoute: typeof CaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browserTabs': {
      id: '/browserTabs'
      path: '/browserTabs'
      fullPath: '/browserTabs'
      preLoaderRoute: typeof BrowserTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baseConverter': {
      id: '/baseConverter'
      path: '/baseConverter'
      fullPath: '/baseConverter'
      preLoaderRoute: typeof BaseConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base64Converter': {
      id: '/base64Converter'
      path: '/base64Converter'
      fullPath: '/base64Converter'
      preLoaderRoute: typeof Base64ConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audioMd5': {
      id: '/audioMd5'
      path: '/audioMd5'
      fullPath: '/audioMd5'
      preLoaderRoute: typeof AudioMd5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asciiTable': {
      id: '/asciiTable'
      path: '/asciiTable'
      fullPath: '/asciiTable'
      preLoaderRoute: typeof AsciiTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SpeechToText': {
      id: '/SpeechToText'
      path: '/SpeechToText'
      fullPath: '/SpeechToText'
      preLoaderRoute: typeof SpeechToTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpeechToTextRoute: SpeechToTextRoute,
  AboutRoute: AboutRoute,
  AsciiTableRoute: AsciiTableRoute,
  AudioMd5Route: AudioMd5Route,
  Base64ConverterRoute: Base64ConverterRoute,
  BaseConverterRoute: BaseConverterRoute,
  BrowserTabsRoute: BrowserTabsRoute,
  CaseConverterRoute: CaseConverterRoute,
  ColorConverterRoute: ColorConverterRoute,
  CssFormatterRoute: CssFormatterRoute,
  CsvJsonConverterRoute: CsvJsonConverterRoute,
  DateCalculatorRoute: DateCalculatorRoute,
  FileUploaderRoute: FileUploaderRoute,
  GradientGeneratorRoute: GradientGeneratorRoute,
  HashCalculatorRoute: HashCalculatorRoute,
  HexStringConverterRoute: HexStringConverterRoute,
  HtmlJsConverterRoute: HtmlJsConverterRoute,
  HttpHeadersRoute: HttpHeadersRoute,
  HttpStatusRoute: HttpStatusRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  ImageGalleryRoute: ImageGalleryRoute,
  ImageMetadataRoute: ImageMetadataRoute,
  ImageToPdfRoute: ImageToPdfRoute,
  JsFormatterRoute: JsFormatterRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  JwtDecoderRoute: JwtDecoderRoute,
  JwtGeneratorRoute: JwtGeneratorRoute,
  LeafletMapRoute: LeafletMapRoute,
  MarkdownToWechatRoute: MarkdownToWechatRoute,
  MqttClientRoute: MqttClientRoute,
  MusicPlayerRoute: MusicPlayerRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  PdfMergerRoute: PdfMergerRoute,
  PdfSplitterRoute: PdfSplitterRoute,
  PdfSplitter_newRoute: PdfSplitter_newRoute,
  PdfToWordRoute: PdfToWordRoute,
  PortTableRoute: PortTableRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  RandomGeneratorRoute: RandomGeneratorRoute,
  RsaKeyGeneratorRoute: RsaKeyGeneratorRoute,
  ScssConverterRoute: ScssConverterRoute,
  StringEncoderRoute: StringEncoderRoute,
  SymmetricCryptoRoute: SymmetricCryptoRoute,
  TextDiffRoute: TextDiffRoute,
  TimestampConverterRoute: TimestampConverterRoute,
  UnitConverterRoute: UnitConverterRoute,
  UrlParserRoute: UrlParserRoute,
  UuidGeneratorRoute: UuidGeneratorRoute,
  VideoToGifRoute: VideoToGifRoute,
  WatermarkRoute: WatermarkRoute,
  WebsocketClientRoute: WebsocketClientRoute,
  WordCounterRoute: WordCounterRoute,
  YamlJsonConverterRoute: YamlJsonConverterRoute,
  CalculateDistanceLazyRoute: CalculateDistanceLazyRoute,
  CoordinateLazyRoute: CoordinateLazyRoute,
  JsonToTsLazyRoute: JsonToTsLazyRoute,
  SignatureLazyRoute: SignatureLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
